# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 4.0'

gem 'httparty', '~> 0.21'
gem 'rubocop', '~> 1.82', require: false
gem 'rubocop-rspec', '~> 3.8', require: false

group :test do
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.23'
end
